routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','Auth\LoginController@showLoginForm');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('sales/reports', 'Sale@reports')->name('reports');
Route::resource('sales', 'Sale');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/carSale.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class carSale extends Model
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/Sale.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\carSale;
use Carbon\Carbon;
use DB;
use  Illuminate\Support\Collection;

class Sale extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data= carSale::paginate(20);
        return view('sales.record', ['data'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('sales.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd($request)
        $sale=new carSale();
        $sale->name=$request->name;
        $sale->address=$request->address;
        $sale->phone=$request->Phone;
        $sale->email=$request->email;
        $sale->model=$request->model;
        $sale->color=$request->color;
        $sale->vin=$request->vin;
        $sale->sfx=$request->sfx;
        $sale->price=$request->price;
        $sale->year= Carbon::now()->year;
        $sale->save();
        return redirect()->route('home')->with('status', 'Add successfully');
    }

    public function reports()
    {
        $data= carSale::all();
        $c=count($data);
        $perModel = new Collection();
        $models = array('NG Corolla','Hilux DC 2.0','LC200 GXR' );
        foreach ($models as $model) {
            $perModel->push(DB::table('car_sales')->where('model', $model)->get());
        }
                          //_ _
        //AWESOME CODE HERE B_B
        $x=DB::table('car_sales')->select('price','created_at')->get()->groupBy(function($val) {
            return Carbon::parse($val->created_at)->format('Y');});
        // dd($x);
        $sales_income_per_year=array();
        foreach ($x as $year) {
          $sales_income_per_year[]=[Carbon::parse($year[0]->created_at)->format('Y'),$year->sum('price')];
        }
        return view('sales.reports', ['sales_count'=>$c,'models'=>$models,'perModel'=>$perModel,'sales_yearly'=>$sales_income_per_year]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data=carSale::find($id);
        return view('sales.show', ['data'=>$data]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <a href="{{route('sales.create')}}" class="btn btn-success">Add sale</a>
                    <a href="{{route('sales.index')}}" class="btn btn-info">View sales record</a>
                    <a href="{{route('reports')}}" class="btn btn-warning">View Reports</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/sales/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Add to sales record</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form class="form-horizontal" action="{{route('sales.store')}}" method="post">
                      <fieldset>
                        {{csrf_field()}}

                      <!-- Text input-->
                      <div class="form-group">
                        <label class="col-md-4 control-label" for="name">Name</label>
                        <div class="col-md-4">
                        <input id="name" name="name" type="text" placeholder="" class="form-control input-md">

                        </div>
                      </div>

                      <!-- Text input-->
                      <div class="form-group">
                        <label class="col-md-4 control-label" for="address">Address</label>
                        <div class="col-md-6">
                        <input id="address" name="address" type="text" placeholder="" class="form-control input-md">

                        </div>
                      </div>

                      <!-- Text input-->
                      <div class="form-group">
                        <label class="col-md-4 control-label" for="Phone">Phone</label>
                        <div class="col-md-4">
                        <input id="Phone" name="Phone" type="text" placeholder="" class="form-control input-md">

                        </div>
                      </div>

                      <!-- Text input-->
                      <div class="form-group">
                        <label class="col-md-4 control-label" for="email">Email</label>
                        <div class="col-md-4">
                        <input id="email" name="email" type="text" placeholder="" class="form-control input-md">

                        </div>
                      </div>

                      <!-- Select Basic -->
                      <div class="form-group">
                        <label class="col-md-4 control-label" for="model">Model</label>
                        <div class="col-md-4">
                          <select id="model" name="model" class="form-control">
                            <option value="LC200 GXR">LC200 GXR</option>
                            <option value="NG Corolla">NG Corolla</option>
                            <option value="Hilux DC 2.0">Hilux DC 2.0</option>
                          </select>
                        </div>
                      </div>

                      <!-- Text input-->
                      <div class="form-group">
                        <label class="col-md-4 control-label" for="color">Color</label>
                        <div class="col-md-4">
                        <input id="color" name="color" type="text" placeholder="" class="form-control input-md">

                        </div>
                      </div>

                      <!-- Text input-->
                      <div class="form-group">
                        <label class="col-md-4 control-label" for="vin">VIN #</label>
                        <div class="col-md-4">
                        <input id="vin" name="vin" type="text" placeholder="" class="form-control input-md">

                        </div>
                      </div>

                      <!-- Multiple Radios (inline) -->
                      <div class="form-group">
                        <label class="col-md-4 control-label" for="sfx">SFX</label>
                        <div class="col-md-4">
                          <label class="radio-inline" for="sfx-0">
                            <input type="radio" name="sfx" id="sfx-0" value="1" checked="checked">
                            1
                          </label>
                          <label class="radio-inline" for="sfx-1">
                            <input type="radio" name="sfx" id="sfx-1" value="2">
                            2
                          </label>
                          <label class="radio-inline" for="sfx-2">
                            <input type="radio" name="sfx" id="sfx-2" value="3">
                            3
                          </label>
                          <label class="radio-inline" for="sfx-3">
                            <input type="radio" name="sfx" id="sfx-3" value="4">
                            4
                          </label>
                        </div>
                      </div>

                      <!-- Text input-->
                      <div class="form-group">
                        <label class="col-md-4 control-label" for="price">Price</label>
                        <div class="col-md-4">
                        <input id="price" name="price" type="text" placeholder="" class="form-control input-md">

                        </div>
                      </div>

                      <!-- Button -->
                      <div class="form-group">
                        <label class="col-md-4 control-label" for=""></label>
                        <div class="col-md-4">
                          <button id="" name="" class="btn btn-primary">Save</button>
                        </div>
                      </div>

                      </fieldset>
                      </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sales/record.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
      <div class="panel-body">
          @if (session('status'))
              <div class="alert alert-success">
                  {{ session('status') }}
              </div>
            @endif
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">Sales record</div>
                  <div class="panel-body">
                    <table class="table table-bordered table-responsive table-condensed ">

                            <tr>
                              <td>No.</td>
                              <td>Name</td>
                              <td>Model</td>
                              <td>Year</td>
                              <td>Purchase Date</td>
                              <td>Actions</td>
                            </tr>

                        <tbody>
                          @foreach ($data as $sale)
                          <tr>
                            <td>{{(($data->currentPage() - 1 ) * $data->perPage() ) + $loop->iteration }}</td>
                            <td>{{$sale->name}}</td>
                            <td>{{$sale->model}}</td>
                            <td>{{$sale->year}}</td>
                            <td>{{$sale->created_at}}</td>
                            <td>
                              <ul class="list-unstyled text-center">
                                <li><a href="{{route('sales.show',$sale->id)}}" class="btn btn-success" style="width: 68px;  margin-bottom: 4px;">View</a> </li>
                                <li><a href="{{route('sales.destroy',$sale->id)}}" class="btn btn-danger" style="width: 68px;  margin-bottom: 0px;">Delete</a></li>
                              </ul>
                            </td>
                          </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <div class="text-center">
                      {{ $data->links() }}
                    </div>
                    <a href="{{route('home')}}" class="btn btn-warning">Go back</a>

                  </div>
              </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/sales/reports.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
      <div class="panel-body">
          @if (session('status'))
              <div class="alert alert-success">
                  {{ session('status') }}
              </div>
            @endif
        <div class="">
            <div class="panel panel-info">
                <div class="panel-heading">Reports</div>
                  <div class="panel-body">
                    <div class="container">
                      <div class="row">
                        <div class="col-md-6">
                          <h3>Total Number of units sold</h3>
                        </div>
                        <div class="col-md-6">
                            <h3>{{$sales_count}} Unit</h3>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-6">
                          <h3>Models</h3>
                        </div>
                        <div class="col-md-6">
                            @foreach ($models as $d)
                              <h3>{{"-".$d}}</h3>
                            @endforeach
                        </div>
                      </div>

                      <div class="row">
                        <div class="col-md-8 ">
                          <h3>Number of units sold - Grouped by model</h3>
                          <canvas id="bar-chart" width="" height="80"></canvas>
                        </div>
                      </div>

                      <div class="row">
                        <div class="col-md-8">
                          <h3>Vehicle sales income per year</h3>
                          <canvas id="pie-chart" width="" height="180"></canvas>
                        </div>
                      </div>
                    </div>
                      <br>
                      <hr>
                      <a href="{{url()->route('home')}}" class="btn btn-warning">Go back</a>
                    </div>
                  </div>
              </div>
            </div>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
  new Chart(document.getElementById("bar-chart"), {
    type: 'bar',
    data: {
      labels: [ @foreach($models as $model)"{{$model}}",@endforeach],
      datasets: [
        {      label: "Sales per model",
          backgroundColor: ["#3e95cd", "#8e5ea2","#c45850"],
          data: [ @foreach($perModel as $model_data){{count($model_data)}},@endforeach 0],
        }
      ]
    },
    options: {
      legend: { display: false },
      title: {
        display: true,
      }
    }
  });
  //end of first Chart

  new Chart(document.getElementById("pie-chart"), {
    type: 'pie',
    data: {
      labels: [@foreach ($sales_yearly as $data)
        {{$data[0]}},
      @endforeach],
      datasets: [{
        label: "Population (millions)",
        backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
        data: [@foreach ($sales_yearly as $data)
          {{$data[1]}},
        @endforeach,]
      }]
    },
    options: {
      title: {
        display: true,
      }
    }
});
  //end of second chart
});


</script>
@endsection

resources/views/sales/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
      <div class="panel-body">
          @if (session('status'))
              <div class="alert alert-success">
                  {{ session('status') }}
              </div>
            @endif
        <div class="col-md-12">
            <div class="panel panel-info">
                <div class="panel-heading">Transaction details</div>
                  <div class="panel-body">
                    <div class="container">
                      <div class="row">
                        <div class="col-md-2">
                          Name
                        </div>
                        <div class="col-md10">
                            {{$data->name}}
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-2">
                          Phone
                        </div>
                        <div class="col-md10">
                            {{$data->phone}}
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-2">
                          Address
                        </div>
                        <div class="col-md10">
                            {{$data->address}}
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-2">
                          Email
                        </div>
                        <div class="col-md10">
                            {{$data->email}}
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-2">
                          Model
                        </div>
                        <div class="col-md10">
                            {{$data->model}}
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-2">
                          Year
                        </div>
                        <div class="col-md10">
                            {{$data->year}}
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-2">
                          SFX
                        </div>
                        <div class="col-md10">
                            {{$data->sfx}}
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-2">
                          Color
                        </div>
                        <div class="col-md10">
                            {{$data->color}}
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-2">
                          VIN #
                        </div>
                        <div class="col-md10">
                            {{$data->vin}}
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-2">
                          Price
                        </div>
                        <div class="col-md10">
                            {{$data->price}}
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-2">
                          Purchase date
                        </div>
                        <div class="col-md10">
                            {{$data->created_at}}
                        </div>
                      </div>
                      <br>
                      <hr>
                      <a href="{{url()->previous()}}" class="btn btn-warning">Go back</a>
                    </div>
                  </div>
              </div>
            </div>
        </div>
    </div>
</div>
@endsection